va = input('Digite algo: ')
print(f'O tipo primitivo do que foi digitado é: {type(va)}')
print('A expressão só tem espaços? ', va.isspace())
print('A expressão é um número? ', va.isnumeric())
print('A expressão é alfabética? ', va.isalpha())
print('A expressão é alfanumerica? ', va.isalnum())
print('A expressão está em maiúscula? ', va.isupper())
print('A expressão está em minúscula? ', va.islower())
print('A expressão está capitalizada? ', va.istitle())